# Generated by Django 4.2.6 on 2023-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(-1, 'Refunded'), (0, 'Created'), (1, 'Paid'), (2, 'Completed'), (3, 'Cancelled'), (11, 'Sold')], default=0),
        ),
    ]
