# Generated by Django 4.2.6 on 2023-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinmarketapp", "0002_userwallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
