# Generated by Django 4.2.6 on 2023-11-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coinmarketapp", "0002_userwallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwallet",
            name="amount",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("payment_intent", models.CharField(max_length=50)),
                ("clientSecret", models.CharField(max_length=50)),
                ("crypto_amount", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[
                            (-1, "Refunded"),
                            (0, "Created"),
                            (1, "paid"),
                            (2, "Completed"),
                            (3, "Cancelled"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "crypto_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coinmarketapp.cryptocurrency",
                    ),
                ),
            ],
        ),
    ]
