# Generated by Django 4.2.7 on 2023-11-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coinmarketapp", "0002_userwallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="trending_crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("rank", models.IntegerField()),
                ("image", models.ImageField(upload_to="crypto_images/")),
                (
                    "price_change_percentage_24h",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
    ]
