# Generated by Django 4.2.6 on 2023-11-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketapp', '0002_userwallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
