# Generated by Django 4.2.6 on 2023-11-14 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coinmarketapp', '0003_delete_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarketapp.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('payment_intent', models.CharField(default='', max_length=50)),
                ('clientSecret', models.CharField(default='', max_length=50)),
                ('crypto_amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.IntegerField(choices=[(-1, 'Refunded'), (0, 'Created'), (1, 'paid'), (2, 'Completed'), (3, 'Cancelled')], default=0)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coinmarketapp.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
