# Generated by Django 4.2.6 on 2023-11-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketapp', '0003_userwallet_amount_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
