# Generated by Django 4.2.6 on 2023-11-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinmarketapp", "0003_alter_cryptocurrency_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
