# Generated by Django 4.2.6 on 2023-11-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketapp', '0004_userwallet_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
