# Generated by Django 4.2.6 on 2023-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketapp', '0005_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
    ]
